version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: ls && cd Sample/DTL/Shape/ && ls && gcc --version && g++ All.cpp -Wall -Wextra -O2 -march=native -I../../../include/ -std=c++11 && g++ All.cpp -Wall -Wextra -O2 -march=native -I../../../include/ -std=c++14
